

application: cartodb-gallery 
version: 1
runtime: python
api_version: 1

handlers:

- url: /crossdomain.xml 
  mime_type: text/xml
  static_files: static/crossdomain.xml 
  upload: static/crossdomain.xml
  
- url: /static
  static_dir: static
  
- url: /js
  static_dir: js
  
- url: /css
  static_dir: css


- url: /.*
  script: main.py

